training: !!bool "false"
pre_processing: !!bool 'false'
checking: !!bool 'false'
device: 0
---
path:
    # script_prefix: '/home/user/zhaoyi.gu/mnt/g2'
    data_prefix: '/data/ssd1/zhaoyi.gu' #在g2上
    out_path: '/home/nis/lele.liao/projects/code_vc/PLDA/data'
    xvecmodel_path: '/home/nis/lele.liao/projects/x-vector/xvector_train_result/model/state_dict--sub_epoch=200.pt'
    traindata_path: '/home/nis/lele.liao/projects/code_vc/PLDA/data/egs_train.pkl'
    # traindata_path: 'DATASET/SEPARATED_LIBRISPEECH/TRAIN_DATA/AUG_DATA/DIR_AUG_DATA/combine/egs/egs.train.pkl'
---
data:
    sr: 16000
    stft_frame: 0.064 #(s)
    stft_hop: 0.016 #(s)
    lda_dim: 128
---   
model:
    # nmels: 40
    nmels: 30
    feat_num: 30